sudo: required
language: generic
services:
- docker
script:
- echo $DJANGO_SECRET_KEY
- echo "DONE"
- docker-compose  run web sh -c "coverage run --source=accounts manage.py test accounts"
#docker-compose  exec web python manage.py
after_success:
  - coveralls
deploy:
  provider: script
  script: bash docker_push.sh
  skip_cleanup: true
  on:
    branch: master
