sudo: required
language: generic
services:
- docker
before_install:
- docker-compose -f docker-compose.dev.yml up --build
script:
- echo $DJANGO_SECRET_KEY
- echo "DONE"
#- docker-compose exec django python manage.py test
deploy:
  provider: script
  script: bash docker_push.sh
  skip_cleanup: true
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
