sudo: required
language: generic
services:
- docker
before_install:
- docker-compose up -d
install:
  - pip install coveralls
script:
- docker ps
- docker-compose  exec web coverage run --source= manage.py test && coveralls
after_success:
- echo $COVERALLS_REPO_TOKEN
- echo $USER
- docker-compose  exec web  coveralls
#  docker-compose  exec web sh -c "coveralls"
deploy:
  provider: script
  script: bash docker_push.sh
  skip_cleanup: true
  on:
    branch: master
