sudo: required
language: generic
services:
- docker
before_install:
- docker-compose  up -d
script:
- echo $DJANGO_SECRET_KEY
- echo "DONE"
- coverage run --source=api manage.py test
#docker-compose  exec web python manage.py
after_success:
  - coveralls
deploy:
  provider: script
  script: bash docker_push.sh
  skip_cleanup: true
  on:
    branch: master
