sudo: required
language: generic
services:
- docker
before_install:
- docker-compose up

script:
- docker ps
- docker-compose  exec web coverage run --source= manage.py test


#- echo $DJANGO_SECRET_KEY
#- echo "DONE"
#- docker-compose  run web sh -c "coverage run --source= manage.py test"

##docker-compose  exec web python manage.py
after_success:
- docker ps
#  docker-compose  exec web sh -c "coveralls"
deploy:
  provider: script
  script: bash docker_push.sh
  skip_cleanup: true
  on:
    branch: master
