sudo: required
language: generic
services:
- docker
before_install:
- docker-compose up -d

script:
- docker ps
- docker-compose  exec web coverage run --source= manage.py test
after_success:
- docker-compose  exec web coveralls
#  docker-compose  exec web sh -c "coveralls"
deploy:
  provider: script
  script: bash docker_push.sh
  skip_cleanup: true
  on:
    branch: master
