sudo: required
language: generic
services:
- docker
#before_install:
#- docker-compose up

script:
- docker-compose  run web coverage run --source= manage.py test 

after_success:
#- docker ps
#- docker-compose  exec web  coveralls
- docker-compose  run web coveralls
deploy:
  provider: script
  script: bash docker_push.sh
  skip_cleanup: true
  on:
    branch: master
