###############################################################################
#  In settings.py:
#       DATABASES = {
#            'default': {
#                'ENGINE': 'django.db.backends.mysql',
#                'HOST': 'mysql',
#                {   ...
#            }
#        }
#
#  In PyCharm configurations:
#       Host: 0.0.0.0 - Port: 8000
#       Python interpreter: Select the docker ...
###############################################################################
version: "3.1"



services:

    django:
      restart: always
      build: .
      container_name: ${PROJECT_NAME}-django
      command: .entrypoint.sh
      env_file:
       - .env
      volumes:
        - ./app:/app
        - static:/srv
      expose:
         - 8001
      depends_on:
        - postgres
        - redis

    postgres:
      image: postgres:11-alpine
      container_name: ${PROJECT_NAME}-teamwork1
      volumes:
        - postgres_data:/var/lib/postgresql/data/


    nginx:
      restart: always
      build: ./nginx
      container_name: ${PROJECT_NAME}-nginx
      volumes:
          - static:/srv:ro
      ports:
           - 8001:8001
      depends_on:
          - django
    redis:
      image: redis:latest
      container_name: ${PROJECT_NAME}-redis
      ports:
        - 6378:6378


volumes:
  postgres_data:
  static:

