# Generated by Django 2.2.6 on 2019-11-11 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gif',
            old_name='user',
            new_name='owner',
        ),
    ]
