# Generated by Django 2.2.6 on 2019-11-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
