# Generated by Django 2.2.6 on 2019-11-14 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20191114_2026'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gif',
            table='gif',
        ),
    ]
