# Generated by Django 2.2.6 on 2019-11-20 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20191119_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='backend.Article'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='gif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='backend.GIF'),
        ),
    ]
